import type { Metadata } from "next";
import NextConfig from "../../next.config";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import { Noto_Sans_JP } from 'next/font/google';
import { ThemeProvider } from '@mui/material/styles';
import CustomAppBar from "./_component/AppBar";
import FooterContent from "./_component/FooterContent";
import theme from './theme';
import Box from '@mui/material/Box';
import "@/styles/_application.scss";

const notoSansJp = Noto_Sans_JP({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-noto-sans',
});

const basePath = NextConfig.basePath;
process.env.BASE_PATH = basePath ? basePath : "";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  console.log("env: ", process.env)
  return (
    <html lang="ja">
      <body className={`${notoSansJp.variable}`}>
        <AppRouterCacheProvider options={{ enableCssLayer: true }}>
          <ThemeProvider theme={theme}>
            <CustomAppBar />
            {children}
            <Box
              component="footer"
              sx={{
                pb: 3,
                mx: 0,
                mt: 'auto',
                backgroundColor: "rgb(66, 66, 66)"
              }}
            >
              <FooterContent />
            </Box>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
