import type { Metadata } from "next";
import NextConfig from "../../next.config";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import { Noto_Sans_JP } from 'next/font/google';
import { ThemeProvider } from '@mui/material/styles';
import CustomAppBar from "./_component/AppBar";
import FooterContent from "./_component/FooterContent";
import Copyright from "./_component/Copylight";
import theme from './theme';
import "@/styles/_application.scss";

const notoSansJp = Noto_Sans_JP({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-noto-sans',
});

const basePath = NextConfig.basePath;
process.env.BASE_PATH = basePath ? basePath : "";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={`${notoSansJp.variable}`}>
        <AppRouterCacheProvider options={{ enableCssLayer: true }}>
          <ThemeProvider theme={theme}>
            <CustomAppBar />
            {children}
            <FooterContent />
            <Copyright />
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
